// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iqyntoxgsqbsnndnneib.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlxeW50b3hnc3Fic25uZG5uZWliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4MzI2NTgsImV4cCI6MjA1ODQwODY1OH0.acFhF09jeN_6tBAS2EHrl6NHS4vDcMXTFbfbYZoLGV4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);